version: '3.1'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - 'mongo-vol:/app/data/bd'
    networks:
            mongo-node-net:
                ipv4_address: 172.40.0.10
    container_name: mi-mongo
  nodejs:
    image: mi-nodejs
    ports:
      - '8080:8080'
    networks:
            mongo-node-net:
                ipv4_address: 172.40.0.11
            node-nginx-net:
                ipv4_address: 172.80.0.10
    container_name: mi-node
  nginx:
    image: nginx
    ports:
      - '8080:80'
    networks:
            node-nginx-net:
                ipv4_address: 172.80.0.11
    container_name: mi-nginx

volumes:
  mongo-vol:
    driver: local
networks:
    mongo-node-net:
      driver: bridge
      ipam:
        config:
          - subnet: 172.40.0.0/16
    node-nginx-net:
      driver: bridge
      ipam:
        config:
          - subnet: 172.80.0.0/16